[package]
name = "awrust"
version = "1.0.0"
edition = "2024"

[dependencies]
http-body-util = "0.1"
hyper = { version = "1", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1", features = ["tokio", "http1", "http2", "client-legacy", "server-auto"] }
socket2 = "0.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "process", "signal", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[dev-dependencies]
tempfile = "3"
